#!/bin/bash

#SBATCH --nodes 2
#SBATCH --partition veryshort
#SBATCH --account COMS30005
#SBATCH --job-name 1024
#SBATCH --time 00:15:00
#SBATCH --output OUT_1024
#SBATCH --exclusive


# Use Intel MPI (make sure you compile with the same module and 'mpiicc')
module load languages/intel/2018-u3


# Print some information about the job
echo "Running on host $(hostname)"
echo "Time is $(date)"
echo "Directory is $(pwd)"
echo "Slurm job ID is $SLURM_JOB_ID"
echo
echo "This job runs on the following machines:"
echo "$SLURM_JOB_NODELIST" | uniq
echo

# Enable using `srun` with Intel MPI
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

echo "start times"
echo

for i in {2..56}
do
  for j in {1..3}
  do
    srun -n $i ./stencil 1024 1024 100
  done
  echo
done

echo
echo "timings done"
